import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Khai báo các font
const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// Metadata cho trang
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Root layout component với thẻ <html> và <body>
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="mdl-js">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
